[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["jupyterlab"]



[tool.uv.sources]
api = { workspace = true }
darts = { workspace = true }

[tool.uv.workspace]
members = ["darts", "api"]
