name: Backend CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  bazel:
    runs-on: self-hosted  # Runs on your Raspberry Pi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Bazel 7.4.1 is Installed
        run: bash sh/bazel_build_version_check.sh


      # - name: Set up Bazel cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/bazel
      #     key: bazel-${{ runner.os }}-${{ github.sha }}
      #     restore-keys: |
      #       bazel-${{ runner.os }}-

      # - name: Build with Bazel 7.4.1
      #   run: bazel build //...

      - name: Run Tests with Bazel 7.4.1
        run: bazel test //...
      # - name: Bazel Test
      #   run: bazel test --test_tag_filters="-ci-skip" --test_output=errors //...
      - name: Format Check
        run: bazel run //rules/format:format.check
